// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI94mB8CAGMOccqCDIuJKvAn9oXvtHfJA',
    appId: '1:703299755477:web:4efba26c2c679fcdcff15c',
    messagingSenderId: '703299755477',
    projectId: 'tallylensapp',
    authDomain: 'tallylensapp.firebaseapp.com',
    storageBucket: 'tallylensapp.firebasestorage.app',
    measurementId: 'G-V8BXQ1LXTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ZjUCCRx7poSfcnu7Tr1GVgTrvUy3C5c',
    appId: '1:703299755477:android:db02da7549a66f1acff15c',
    messagingSenderId: '703299755477',
    projectId: 'tallylensapp',
    storageBucket: 'tallylensapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqV-E12548do95GD347KJ-UMi2F7Oz-c',
    appId: '1:703299755477:ios:a0d890d90f7dc6b8cff15c',
    messagingSenderId: '703299755477',
    projectId: 'tallylensapp',
    storageBucket: 'tallylensapp.firebasestorage.app',
    iosBundleId: 'com.example.recibosFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqV-E12548do95GD347KJ-UMi2F7Oz-c',
    appId: '1:703299755477:ios:a0d890d90f7dc6b8cff15c',
    messagingSenderId: '703299755477',
    projectId: 'tallylensapp',
    storageBucket: 'tallylensapp.firebasestorage.app',
    iosBundleId: 'com.example.recibosFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI94mB8CAGMOccqCDIuJKvAn9oXvtHfJA',
    appId: '1:703299755477:web:21cf47e26ac7a96dcff15c',
    messagingSenderId: '703299755477',
    projectId: 'tallylensapp',
    authDomain: 'tallylensapp.firebaseapp.com',
    storageBucket: 'tallylensapp.firebasestorage.app',
    measurementId: 'G-18GGS9TRDM',
  );
}
